/********************************************************************************************
*  ________  _____   ____  ____ 
* |_   __  ||_   _| |_  _||_  _|
*   | |_ \_|  | |     \ \  / /  
*   |  _| _   | |   _  \ \/ /   
*  _| |__/ | _| |__/ | _|  |_   
* |________||________||______|        
* 
* NVMe test tool 2.0
* https://github.com/elyyang
* elyyang@gmail.com
*********************************************************************************************/

#pragma once

#include <stdint.h>

#ifndef __cplusplus
    #if !defined(static_assert)
        #define static_assert _Static_assert
    #endif
#endif // __cplusplus

/********************************************************************
* NVME 2.4 - NVMe Completion
********************************************************************/

#define NVME_COMPLETION_DWORDS_COUNT         (4)
#define NVME_COMPLETION_BYTE_SIZE            (NVME_COMPLETION_DWORDS_COUNT * 4)

//nvme base spec 2.4 section 4.2.3
typedef enum
{
    NVME_COMPLETION_STATUS_TYPE_GENERIC_COMMAND = 0x0,
    NVME_COMPLETION_STATUS_TYPE_COMMAND_SPECIFIC = 0x1,
    NVME_COMPLETION_STATUS_TYPE_MEDIA_ERROR = 0x2,
    NVME_COMPLETION_STATUS_TYPE_PATH_RELATED = 0x3,    
    NVME_COMPLETION_STATUS_TYPE_VENDOR_SPECIFIC = 0x7
} statusCodeType_e;

//nvme base spec 2.4 section 4.2.3.1
typedef enum
{
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_SUCCESSFUL_COMPLETION = 0x00,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_INVALID_COMMAND_OPCODE = 0x01,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_INVALID_FIELD_IN_COMMAND = 0x02,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_COMMAND_ID_CONFLICT = 0x03,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_DATA_TRANSFER_ERROR = 0x04,    
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_COMMANDS_ABORTED_DUE_TO_POWERLOSS = 0x05,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_INTERNAL_ERROR = 0x06,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_COMMAND_ABORT_REQUESTED = 0x07,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_COMMAND_ABORT_DUE_TO_SQ_DELETION = 0x08,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_COMMAND_ABORT_DUE_TO_FAILED_FUSED = 0x9,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_COMMAND_ABORT_DUE_TO_MISSING_FUSED = 0x0a,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_INVALID_NAMESPACE_OR_FORMAT = 0x0b,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_COMMAND_SEQUENCE_ERROR = 0x0c,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_INVALID_SGL_SEGMENT_DESCRIPTOR = 0x0d,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_INVALID_NUM_OF_SGL_DESCRIPTORS = 0x0e,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_DATA_SGL_LENGTH_INVALID = 0x0f,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_METADATA_SGL_LENGTH_INVALID = 0x10,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_SGL_DESCRIPTOR_TYPE_INVALID = 0x11,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_INVALID_USE_OF_CMB = 0x12,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_PRP_OFFSET_INVALID = 0x13,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_ATOMIC_WRITE_UNIT_EXCEEDED = 0x14,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_OPERATION_DENIED = 0x15,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_SGL_OFFSET_INVALID = 0x16,
    //note: 0x17 is reserved
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_HOST_IDENTIFIER_INCONSISTENT_FORMAT = 0x18,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_KEEP_ALIVE_TIMER_EXPIRED = 0x19,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_KEEP_ALIVE_TIMEOUT_INVALID = 0x1a,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_COMMAND_ABORT_DUE_TO_PREEMPT_AND_ABORT = 0x1b,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_SANITIZE_FAILED = 0x1c,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_SANITIZE_IN_PROGRESS = 0x1d,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_SGL_DATA_BLOCK_GRANULARITY_INVALID = 0x1e,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_COMMAND_NOT_SUPPORTED_FOR_QUEUE_IN_CMB = 0x1f,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_NAMESPACE_IS_WRITE_PROTECTED = 0x20,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_COMMAND_INTERRUPTED = 0x21,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_TRANSIENT_TRANSPORT_ERROR = 0x22,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_COMMAND_PROHIBITED_BY_LOCKDOWN = 0x23,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_ADMIN_COMMAND_MEDIA_NOT_READY = 0x24,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_INVALID_KEY_TAG = 0x25,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_HOST_DISPERSED_NAMESPACE_NOT_ENABLED = 0x26,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_HOST_IDENTIFIER_NOT_INITIALIZED = 0x27,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_INCORRECT_KEY = 0x28,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_FDP_DISABLED = 0x29,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_INVALID_PLACEMENT_HANDLE_LIST = 0x2a,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_SANITIZE_NAMESPACE_FAILED = 0x2b,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_SANITIZE_NAMESPACE_IN_PROGRESS = 0x2c,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_FAILED_TO_RESTORE_CONFIGURATION = 0x2d,
    //note: 0x2e-0x7f are reserved
    //I/O command set specific status (nvm command set)
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_LBA_OUT_OF_RANGE = 0x80,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_CAPACITY_EXCEEDED = 0x81,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_NAMESPACE_NOT_READY = 0x82,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_RESERVATION_CONFLICT = 0x83,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_FORMAT_IN_PROGRESS = 0x84,
    //I/O command set specific status (key value command set)
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_INVALID_VALUE_SIZE = 0x85,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_INVALID_KEY_SIZE = 0x86,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_KV_KEY_DOES_NOT_EXIST = 0x87,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_UNRECOVERED_ERROR = 0x88,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_KEY_EXISTS = 0x89,
    //note: 0x8a-0xbf are reserved
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_VENDOR_SPECIFIC_FIRST = 0xc0,
    NVME_COMPLETION_GENERIC_COMMAND_STATUS_VENDOR_SPECIFIC_LAST = 0xff
} genericCommandStatusCode_e;

//nvme base spec 2.4 section 4.2.3.2
typedef enum
{
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_COMPLETION_QUEUE_INVALID = 0x00, // Create I/O Submission Queue
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_QUEUE_IDENTIFIER = 0x01, // Create I/O Submission Queue, Create I/O Completion Queue, Connect, Delete I/O Completion Queue, Delete I/O Submission Queue
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_QUEUE_SIZE = 0x02, // Create I/O Submission Queue, Create I/O Completion Queue
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_ABORT_COMMAND_LIMIT_EXCEEDED = 0x03, // Abort
    // 0x04 is reserved
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_ASYNCHRONOUS_EVENT_REQUEST_LIMIT_EXCEEDED = 0x05, // Asynchronous Event Request
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_FIRMWARE_SLOT = 0x06, // Firmware Commit
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_FIRMWARE_IMAGE = 0x07, // Firmware Commit
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_INTERRUPT_VECTOR = 0x08, // Create I/O Completion Queue
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_LOG_PAGE = 0x09, // Get Log Page
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_FORMAT = 0x0a, // Format NVM, Namespace Management
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_FIRMWARE_ACTIVATION_REQUIRES_CONVENTIONAL_RESET = 0x0b, // Firmware Commit, Sanitize, Sanitize Namespace
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_QUEUE_DELETION = 0x0c, // Delete I/O Completion Queue
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_FEATURE_IDENTIFIER_NOT_SAVEABLE = 0x0d, // Set Features
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_FEATURE_NOT_CHANGEABLE = 0x0e, // Set Features
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_FEATURE_NOT_NAMESPACE_SPECIFIC = 0x0f, // Set Features
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_FIRMWARE_ACTIVATION_REQUIRES_NVM_SUBSYSTEM_RESET = 0x10, // Firmware Commit, Sanitize, Sanitize Namespace
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_FIRMWARE_ACTIVATION_REQUIRES_CONTROLLER_LEVEL_RESET = 0x11, // Firmware Commit, Sanitize, Sanitize Namespace
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_FIRMWARE_ACTIVATION_REQUIRES_MAXIMUM_TIME_VIOLATION = 0x12, // Firmware Commit
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_FIRMWARE_ACTIVATION_PROHIBITED = 0x13, // Firmware Commit
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_OVERLAPPING_RANGE = 0x14, // Firmware Commit, Firmware Image Download, Set Features
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_NAMESPACE_INSUFFICIENT_CAPACITY = 0x15, // Namespace Management
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_NAMESPACE_IDENTIFIER_UNAVAILABLE = 0x16, // Namespace Management
    // 0x17 is reserved
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_NAMESPACE_ALREADY_ATTACHED = 0x18, // Namespace Attachment
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_NAMESPACE_IS_PRIVATE = 0x19, // Namespace Attachment
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_NAMESPACE_NOT_ATTACHED = 0x1a, // Namespace Attachment
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_THIN_PROVISIONING_NOT_SUPPORTED = 0x1b, // Namespace Management
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_CONTROLLER_LIST_INVALID = 0x1c, // Namespace Attachment
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_DEVICE_SELF_TEST_IN_PROGRESS = 0x1d, // Device Self-test
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_BOOT_PARTITION_WRITE_PROHIBITED = 0x1e, // Firmware Commit
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_CONTROLLER_IDENTIFIER = 0x1f, // Virtualization Management, Track Send, Track Receive, Migration Send, Migration Receive, Controller Data Queue, Get Feature, Set Features, Lockdown, Get Log Page
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_SECONDARY_CONTROLLER_STATE = 0x20, // Virtualization Management
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_NUMBER_OF_CONTROLLER_RESOURCES = 0x21, // Virtualization Management
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_RESOURCE_IDENTIFIER = 0x22, // Virtualization Management
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_SANITIZE_PROHIBITED_WHILE_PERSISTENT_MEMORY_REGION_IS_ENABLED = 0x23, // Sanitize
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_ANA_GROUP_IDENTIFIER_INVALID = 0x24, // Namespace Management
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_ANA_ATTACH_FAILED = 0x25, // Namespace Attachment
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INSUFFICIENT_CAPACITY = 0x26, // Capacity Management
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_NAMESPACE_ATTACHMENT_LIMIT_EXCEEDED = 0x27, // Namespace Attachment
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_PROHIBITION_OF_COMMAND_EXECUTION_NOT_SUPPORTED = 0x28, // Lockdown
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_IO_COMMAND_SET_NOT_SUPPORTED = 0x29, // Namespace Attachment, Namespace Management
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_IO_COMMAND_SET_NOT_ENABLED = 0x2a, // Namespace Attachment
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_IO_COMMAND_SET_COMBINATION_REJECTED = 0x2b, // Set Features
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_IO_COMMAND_SET = 0x2c, // Identify
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_IDENTIFIER_UNAVAILABLE = 0x2d, // Capacity Management
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_NAMESPACE_IS_DISPERSED = 0x2e, // Reservation Acquire, Reservation Register, Reservation Release, Reservation Report
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_DISCOVERY_INFORMATION = 0x2f, // Discovery Information Management
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_ZONING_DATA_STRUCTURE_LOCKED = 0x30, // Fabric Zoning Lookup, Fabric Zoning Send, Fabric Zoning Receive
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_ZONING_DATA_STRUCTURE_NOT_FOUND = 0x31, // Fabric Zoning Lookup, Fabric Zoning Send, Fabric Zoning Receive
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INSUFFICIENT_DISCOVERY_RESOURCES = 0x32, // Discovery Information Management
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_REQUESTED_FUNCTION_DISABLED = 0x33, // Fabric Zoning Lookup, Fabric Zoning Send, Fabric Zoning Receive
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_ZONE_GROUP_ORIGINATOR_INVALID = 0x34, // Fabric Zoning Send
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_HOST = 0x35, // Manage Exported NVM Subsystem Send
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_NVM_SUBSYSTEM = 0x36, // Manage Exported NVM Subsystem Send
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_CONTROLLER_DATA_QUEUE = 0x37, // Set Features, Get Features, Track Send, Controller Data Queue
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_NOT_ENOUGH_RESOURCES = 0x38, // Track Send, Controller Data Queue, Manage Exported NVM Subsystem Receive, Manage Exported Namespace, Migration Send
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_CONTROLLER_SUSPENDED = 0x39, // Track Send, Sanitize
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_CONTROLLER_NOT_SUSPENDED = 0x3a, // Track Send
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_CONTROLLER_DATA_QUEUE_FULL = 0x3b, // Track Send
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_REQUEST_EXCEEDS_MAXIMUM_NAMESPACE_SANITIZE_OPERATIONS_IN_PROGRESS = 0x3c, // Sanitize Namespace
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_MANUFACTURING_DEFAULT_PERSONALITY_REQUIRED = 0x3d, // Firmware Commit
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_POWER_LIMIT = 0x3e, // Set Features
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_CROSS_CONTROLLER_RESET_IN_PROGRESS = 0x3f, // Cross-Controller Reset
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_CROSS_CONTROLLER_RESET_LOG_PAGE_FULL = 0x40, // Cross-Controller Reset
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_CROSS_CONTROLLER_RESET_LIMIT_EXCEEDED = 0x41, // Cross-Controller Reset
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_CONTROLLER_ACTIVE = 0x42, // Manage Exported NVM Subsystem Send
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_EXPORTED_ASSOCIATION = 0x43, // Manage Exported NVM Subsystem Send
    NVME_COMPLETION_COMMAND_SPECIFIC_STATUS_INVALID_EXPORTED_CONFIGURATION_STATE = 0x44, // Manage Exported NVM Subsystem Send
    // 0x45-0x6f are reserved
    // 0x70-0x7f directive specific    
    // 0x80-0xbf I/O command set or Fabrics command specific
    // 0xc0-0xff vendor specific
} commandSpecificStatusCode_e;

typedef enum
{
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_CONFLICTING_ATTRIBUTES = 0x80, 
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_INVALID_PROTECTION_INFORMATION = 0x81,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_ATTEMPTED_WRITE_TO_READ_ONLY_RANGE = 0x82,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_COMMAND_SIZE_LIMIT_EXCEEDED = 0x83,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_INVALID_COMMAND_ID = 0x84,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_INCOMPATIBLE_NAMESPACE_OR_FORMAT = 0x85,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_FAST_COPY_NOT_POSSIBLE = 0x86,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_OVERLAPPING_IO_RANGE = 0x87,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_NAMESPACE_NOT_REACHABLE = 0x88,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_INSUFFICIENT_RESOURCES = 0x89,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_INSUFFICIENT_PROGRAM_RESOURCES = 0x8a,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_INVALID_MEMORY_NAMESPACE = 0x8b,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_INVALID_MEMORY_RANGE_SET = 0x8c,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_INVALID_MEMORY_RANGE_SET_IDENTIFIER = 0x8d,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_INVALID_PROGRAM_DATA = 0x8e,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_INVALID_PROGRAM_INDEX = 0x8f,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_INVALID_PROGRAM_TYPE = 0x90,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_MAXIMUM_MEMORY_RANGES_EXCEEDED = 0x91,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_MAXIMUM_MEMORY_RANGE_SETS_EXCEEDED = 0x92,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_MAXIMUM_PROGRAMS_ACTIVATED = 0x93,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_MAXIMUM_PROGRAM_BYTES_EXCEEDED = 0x94,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_MEMORY_RANGE_SET_IN_USE = 0x95,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_NO_PROGRAM = 0x96,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_OVERLAPPING_MEMORY_RANGES = 0x97,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_PROGRAM_NOT_ACTIVATED = 0x98,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_PROGRAM_IN_USE = 0x99,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_PROGRAM_INDEX_NOT_DOWNLOADABLE = 0x9a,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_PROGRAM_TOO_BIG = 0x9b,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_SUCCESSFUL_MEDIA_VERIFICATION_READ = 0x9c,
    // 0x9d-0xb7 are reserved
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_ZONED_BOUNDARY_ERROR = 0xb8,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_ZONE_IS_FULL = 0xb9,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_ZONE_IS_READ_ONLY = 0xba,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_ZONE_IS_OFFLINE = 0xbb,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_ZONE_INVALID_WRITE = 0xbc,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_TOO_MANY_ACTIVE_ZONES = 0xbd,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_TOO_MANY_OPEN_ZONES = 0xbe,
    NVME_COMPLETION_IO_COMMAND_SPECIFIC_STATUS_INVALID_ZONE_STATE_TRANSITION = 0xbf
} ioCommandSpecificStatusCode_e;

//nvme base spec 2.4 section 4.2.3.3
typedef enum
{
    //00h to 7Fh Reserved
    NVME_COMPLETION_MEDIA_AND_DATA_INTEGRITY_ERROR_STATUS_CODE_WRITE_FAULT = 0x80,
    NVME_COMPLETION_MEDIA_AND_DATA_INTEGRITY_ERROR_STATUS_CODE_UNRECOVERED_READ_ERROR = 0x81,
    NVME_COMPLETION_MEDIA_AND_DATA_INTEGRITY_ERROR_STATUS_CODE_END_TO_END_GUARD_CHECK_ERROR = 0x82,
    NVME_COMPLETION_MEDIA_AND_DATA_INTEGRITY_ERROR_STATUS_CODE_END_TO_END_APPLICATION_TAG_CHECK_ERROR = 0x83,
    NVME_COMPLETION_MEDIA_AND_DATA_INTEGRITY_ERROR_STATUS_CODE_END_TO_END_REFERENCE_TAG_CHECK_ERROR = 0x84,
    NVME_COMPLETION_MEDIA_AND_DATA_INTEGRITY_ERROR_STATUS_CODE_COMPARE_FAILURE = 0x85,
    NVME_COMPLETION_MEDIA_AND_DATA_INTEGRITY_ERROR_STATUS_CODE_ACCESS_DENIED = 0x86,
    NVME_COMPLETION_MEDIA_AND_DATA_INTEGRITY_ERROR_STATUS_CODE_DEALLOCATED_OR_UNWRITTEN_LOGICAL_BLOCK = 0x87,
    NVME_COMPLETION_MEDIA_AND_DATA_INTEGRITY_ERROR_STATUS_CODE_END_TO_END_STORAGE_TAG_CHECK_ERROR = 0x88,
    //0x89 to 0xBF Reserved
    //0xC0 to 0xFF Vendor Specific
    
} mediaAndDataIntegrityErrorStatusCode_e;


typedef struct __attribute__((packed, aligned(4)))
{
    //dw2
    uint32_t sqHeadPointer          : 16;
    uint32_t sqIdentifier           : 16;
    
    //dw3   
    uint32_t commandIdentifier      : 16;    
    uint32_t phaseTag               : 1;  
    uint32_t statusCode             : 8;
    uint32_t statusCodeType         : 3;
    uint32_t commandRetryDelay      : 2; 
    uint32_t more                   : 1; 
    uint32_t doNotRetry             : 1; 
} completionCommon_t;

/********************************************************************
* NVMe completion
*********************************************************************/
typedef union nvmeCompletion_t
{
    uint32_t dword[4];

    struct
    {
        //dw0
        uint32_t commandSpecific0;

        //dw1
        uint32_t commandSpecific1;
        
        //dw2-3
        completionCommon_t  common;
    }; 
} nvmeCompletion_t;
static_assert(sizeof(nvmeCompletion_t) == NVME_COMPLETION_BYTE_SIZE, "Unexpected nvmeCompletion_t size");
