
#pragma once

//==============================================================================
// PCIe capability structure IDs
//==============================================================================

#define PCIE_CONFIG_HEADER_OFFSET_VENDOR_ID             (0x0)
#define PCIE_CONFIG_HEADER_OFFSET_DEVICE_ID             (0x2)
#define PCIE_CONFIG_HEADER_OFFSET_COMMAND               (0x4)
#define PCIE_CONFIG_HEADER_OFFSET_STATUS                (0x6)
#define PCIE_CONFIG_HEADER_OFFSET_REV_ID                (0x8)
#define PCIE_CONFIG_HEADER_OFFSET_CLASS_CODE            (0x9)
#define PCIE_CONFIG_HEADER_OFFSET_CACHE_LINE_SIZE       (0xC)
#define PCIE_CONFIG_HEADER_OFFSET_LATENCY_TIMER         (0xD)
#define PCIE_CONFIG_HEADER_OFFSET_HEADER_TYPE           (0xE)
#define PCIE_CONFIG_HEADER_OFFSET_BIST                  (0xF)
#define PCIE_CONFIG_HEADER_OFFSET_BAR0                  (0x10)
#define PCIE_CONFIG_HEADER_OFFSET_BAR1                  (0x14)
#define PCIE_CONFIG_HEADER_OFFSET_BAR2                  (0x18)
#define PCIE_CONFIG_HEADER_OFFSET_BAR3                  (0x1C)
#define PCIE_CONFIG_HEADER_OFFSET_BAR4                  (0x20)
#define PCIE_CONFIG_HEADER_OFFSET_BAR5                  (0x24)
#define PCIE_CONFIG_HEADER_OFFSET_CARDBUS_CIS_PTR       (0x28)
#define PCIE_CONFIG_HEADER_OFFSET_SUBSYSTEM_VENDOR_ID   (0x2C)
#define PCIE_CONFIG_HEADER_OFFSET_SUBSYSTEM_ID          (0x2E)
#define PCIE_CONFIG_HEADER_OFFSET_EXPANSION_ROM         (0x30)
#define PCIE_CONFIG_HEADER_OFFSET_CAP_PTR               (0x34)
#define PCIE_CONFIG_HEADER_OFFSET_INT_LINE              (0x3C)
#define PCIE_CONFIG_HEADER_OFFSET_INT_PIN               (0x3D)
#define PCIE_CONFIG_HEADER_OFFSET_MIN_GNT               (0x3E)
#define PCIE_CONFIG_HEADER_OFFSET_MAX_LAT               (0x3F)

#define PCIE_CAPID_RESERVED                             (0x0)
#define PCIE_CAPID_POWER_MANAGEMENT                     (0x1)
#define PCIE_CAPID_AGP                                  (0x2)
#define PCIE_CAPID_VPD                                  (0x3)
#define PCIE_CAPID_SLOT_ID                              (0x4)
#define PCIE_CAPID_MSI                                  (0x5)
#define PCIE_CAPID_COMPACTPCI_HOT_SWAP                  (0x6)
#define PCIE_CAPID_PCIX_DEVICE                          (0x7)
#define PCIE_CAPID_HYPER_TRANSPORT                      (0x8)
#define PCIE_CAPID_VENDOR_SPECIFIC                      (0x9)
#define PCIE_CAPID_DEBUG_PORT                           (0xA)
#define PCIE_CAPID_COMPACTPCI_CENTRAL_RESOURCE_CTRL     (0xB)
#define PCIE_CAPID_PCI_HOT_PLUG                         (0xC)
#define PCIE_CAPID_PCI_BRIDGE_SUBSYSTEM_VENDOR_ID       (0xD)
#define PCIE_CAPID_PCI_EXPRESS                          (0x10)
#define PCIE_CAPID_MSIX                                 (0x11)
#define PCIE_CAPID_SATA_DATA_INDEX                      (0x12)
#define PCIE_CAPID_ADVANCED_FEATURES                    (0x13)
#define PCIE_CAPID_ENHANCED_ALLOCATION_STRUCTURE        (0x14)    

//==============================================================================
// PCIe extended capability structure IDs
//==============================================================================

#define PCIE_EXTCAPID_NULL                              (0x0)
#define PCIE_EXTCAPID_AER                               (0x1)    
#define PCIE_EXTCAPID_VC                                (0x2)
#define PCIE_EXTCAPID_DEVICE_SERIAL_NUMBER              (0x3)
#define PCIE_EXTCAPID_POWER_BUDGETING                   (0x4)
#define PCIE_EXTCAPID_RC_LINK_DECLARATION               (0x5)
#define PCIE_EXTCAPID_PCIE_RC_INTERNAL_LINK_CONTROL     (0x6)    
#define PCIE_EXTCAPID_RC_EVENT_COLLECTOR                (0x7)
#define PCIE_EXTCAPID_MFVC                              (0x8)    
#define PCIE_EXTCAPID_VIRTUAL_CHANNEL                   (0x9)
#define PCIE_EXTCAPID_RCRB_HEADER                       (0xA)
#define PCIE_EXTCAPID_VENDOR_SPECIFIC                   (0xB)
#define PCIE_EXTCAPID_ACS                               (0xD)
#define PCIE_EXTCAPID_ARI                               (0xE)
#define PCIE_EXTCAPID_ATS                               (0xF)
#define PCIE_EXTCAPID_SRIOV                             (0x10)    
#define PCIE_EXTCAPID_MULTICAST                         (0x12)
#define PCIE_EXTCAPID_PAGE_REQUEST                      (0x13)
#define PCIE_EXTCAPID_RESIZABLE_BAR                     (0x15)
#define PCIE_EXTCAPID_DYNAMIC_POWER_ALLOCATION          (0x16)
#define PCIE_EXTCAPID_TPH                               (0x17)
#define PCIE_EXTCAPID_LTR                               (0x18)
#define PCIE_EXTCAPID_SECONDARY_PCIE                    (0x19)
#define PCIE_EXTCAPID_PROTOCOL_MULTIPLEXING             (0x1A)
#define PCIE_EXTCAPID_PASID                             (0x1B)
#define PCIE_EXTCAPID_LNR                               (0x1C)
#define PCIE_EXTCAPID_DPC                               (0x1D)
#define PCIE_EXTCAPID_L1_PM_SUBSTATES                   (0x1E)
#define PCIE_EXTCAPID_PRECISION_TIME_MEASUREMENT        (0x1F)
#define PCIE_EXTCAPID_MPCIE                             (0x20)
#define PCIE_EXTCAPID_FUNCTION_READINESS_STATUS         (0x21)
#define PCIE_EXTCAPID_READINESS_TIME_REPORTING          (0x22)

//==============================================================================
// PCIe header status bit
//==============================================================================

#define PCIE_STATUS_IMMEDIATE_READINESS                 (0x1)
#define PCIE_STATUS_INTERRUPT_STATUS                    (0x8)
#define PCIE_STATUS_CAPABILITIES_LIST                   (0x10)
#define PCIE_STATUS_MASTER_DATA_PARITY_ERROR            (0x100)
#define PCIE_STATUS_SIGNALED_TARGET_ABORT               (0x800)
#define PCIE_STATUS_RECEIVED_TARGET_ABORT               (0x1000)
#define PCIE_STATUS_RECEIVED_MASTER_ABORT               (0x2000)
#define PCIE_STATUS_SIGNALED_SYSTEM_ERROR               (0x4000)
#define PCIE_STATUS_DETECTED_PARITY_ERROR               (0x8000)

//==============================================================================
// PCIe header class code
//==============================================================================

#define PCIE_CLASS_CODE_MASS_STORAGE_CONTROLLER                         (0x1)
#define PCIE_CLASS_CODE_NETWORK_CONTROLLER                              (0x2)
#define PCIE_CLASS_CODE_DISPLAY_CONTROLLER                              (0x3)
#define PCIE_CLASS_CODE_MULTIMEDIA_DEVICE                               (0x4)
#define PCIE_CLASS_CODE_MEMORY_CONTROLLER                               (0x5)
#define PCIE_CLASS_CODE_BRIDGE_DEVICE                                   (0x6)
#define PCIE_CLASS_CODE_SIMPLE_COMMUNICATION_CONTROLLER                 (0x7)
#define PCIE_CLASS_CODE_BASE_SYSTEM_PERIPHERAL                          (0x8)
#define PCIE_CLASS_CODE_INPUT_DEVICE                                    (0x9)
#define PCIE_CLASS_CODE_DOCKING_STATION                                 (0xA)
#define PCIE_CLASS_CODE_PROCESSOR                                       (0xB)
#define PCIE_CLASS_CODE_SERIAL_BUS_CONTROLLER                           (0xC)
#define PCIE_CLASS_CODE_WIRELESS_CONTROLLER                             (0xD)
#define PCIE_CLASS_CODE_INTELLIGENT_IO_CONTROLLER                       (0xE)
#define PCIE_CLASS_CODE_SATELLITE_COMMUNICATION_CONTROLLER              (0xF)
#define PCIE_CLASS_CODE_ENCRYPTION_DECRYPTION_CONTROLLER                (0x10)
#define PCIE_CLASS_CODE_DATA_ACQUISITION_SIGNAL_PROCESSING_CONTROLLER   (0x11)
#define PCIE_CLASS_CODE_UNDEFINED                                       (0xFF)
