
#pragma once

/**************************************************************
PCIe config space header (type 0)
**************************************************************/

#define PCIE_CONFIG_HEADER_OFFSET_VENDOR_ID             (0x0)
#define PCIE_CONFIG_HEADER_OFFSET_DEVICE_ID             (0x2)
#define PCIE_CONFIG_HEADER_OFFSET_COMMAND               (0x4)
#define PCIE_CONFIG_HEADER_OFFSET_STATUS                (0x6)
#define PCIE_CONFIG_HEADER_OFFSET_REV_ID                (0x8)
#define PCIE_CONFIG_HEADER_OFFSET_CLASS_CODE            (0x9)
#define PCIE_CONFIG_HEADER_OFFSET_CACHE_LINE_SIZE       (0xC)
#define PCIE_CONFIG_HEADER_OFFSET_LATENCY_TIMER         (0xD)
#define PCIE_CONFIG_HEADER_OFFSET_HEADER_TYPE           (0xE)
#define PCIE_CONFIG_HEADER_OFFSET_BIST                  (0xF)
#define PCIE_CONFIG_HEADER_OFFSET_BAR0                  (0x10)
#define PCIE_CONFIG_HEADER_OFFSET_BAR1                  (0x14)
#define PCIE_CONFIG_HEADER_OFFSET_BAR2                  (0x18)
#define PCIE_CONFIG_HEADER_OFFSET_BAR3                  (0x1C)
#define PCIE_CONFIG_HEADER_OFFSET_BAR4                  (0x20)
#define PCIE_CONFIG_HEADER_OFFSET_BAR5                  (0x24)
#define PCIE_CONFIG_HEADER_OFFSET_CARDBUS_CIS_PTR       (0x28)
#define PCIE_CONFIG_HEADER_OFFSET_SUBSYSTEM_VENDOR_ID   (0x2C)
#define PCIE_CONFIG_HEADER_OFFSET_SUBSYSTEM_ID          (0x2E)
#define PCIE_CONFIG_HEADER_OFFSET_EXPANSION_ROM         (0x30)
#define PCIE_CONFIG_HEADER_OFFSET_CAP_PTR               (0x34)
#define PCIE_CONFIG_HEADER_OFFSET_INT_LINE              (0x3C)
#define PCIE_CONFIG_HEADER_OFFSET_INT_PIN               (0x3D)
#define PCIE_CONFIG_HEADER_OFFSET_MIN_GNT               (0x3E)
#define PCIE_CONFIG_HEADER_OFFSET_MAX_LAT               (0x3F)

/**************************************************************
PCIe capability structure IDs
**************************************************************/

#define PCIE_CAP_ID_RESERVED                            (0x00)
#define PCIE_CAP_ID_POWER_MANAGEMENT                    (0x01)
#define PCIE_CAP_ID_AGP                                 (0x02)
#define PCIE_CAP_ID_VPD                                 (0x03)
#define PCIE_CAP_ID_SLOT_ID                             (0x04)
#define PCIE_CAP_ID_MSI                                 (0x05)
#define PCIE_CAP_ID_COMPACTPCI_HOT_SWAP                 (0x06)
#define PCIE_CAP_ID_PCIX_DEVICE                         (0x07)
#define PCIE_CAP_ID_HYPER_TRANSPORT                     (0x08)
#define PCIE_CAP_ID_VENDOR_SPECIFIC                     (0x09)
#define PCIE_CAP_ID_DEBUG_PORT                          (0x0A)
#define PCIE_CAP_ID_COMPACTPCI_CENTRAL_RESOURCE_CTRL    (0x0B)
#define PCIE_CAP_ID_PCI_HOT_PLUG                        (0x0C)
#define PCIE_CAP_ID_PCI_BRIDGE_SUBSYSTEM_VENDOR_ID      (0x0D)
#define PCIE_CAP_ID_PCI_EXPRESS                         (0x10)
#define PCIE_CAP_ID_MSIX                                (0x11)
#define PCIE_CAP_ID_SATA_DATA_INDEX                     (0x12)
#define PCIE_CAP_ID_ADVANCED_FEATURES                   (0x13)
#define PCIE_CAP_ID_ENHANCED_ALLOCATION_STRUCTURE       (0x14)    
#define PCIE_CAP_ID_FLATTENING_PORTAL_BRIDGE            (0x15)    

/**************************************************************
PCIe extended capability structure IDs
**************************************************************/

#define PCIE_EXT_CAP_ID_NULL                            (0x00)
#define PCIE_EXT_CAP_ID_AER                             (0x01)    
#define PCIE_EXT_CAP_ID_VC                              (0x02)
#define PCIE_EXT_CAP_ID_DEVICE_SERIAL_NUMBER            (0x03)
#define PCIE_EXT_CAP_ID_POWER_BUDGETING                 (0x04)
#define PCIE_EXT_CAP_ID_RC_LINK_DECLARATION             (0x05)
#define PCIE_EXT_CAP_ID_PCIE_RC_INTERNAL_LINK_CONTROL   (0x06)    
#define PCIE_EXT_CAP_ID_RC_EVENT_COLLECTOR              (0x07)
#define PCIE_EXT_CAP_ID_MFVC                            (0x08)    
#define PCIE_EXT_CAP_ID_VIRTUAL_CHANNEL                 (0x09)
#define PCIE_EXT_CAP_ID_RCRB_HEADER                     (0x0A)
#define PCIE_EXT_CAP_ID_VENDOR_SPECIFIC                 (0x0B)
#define PCIE_EXT_CAP_ID_ACS                             (0x0D)
#define PCIE_EXT_CAP_ID_ARI                             (0x0E)
#define PCIE_EXT_CAP_ID_ATS                             (0x0F)
#define PCIE_EXT_CAP_ID_SRIOV                           (0x10)    
#define PCIE_EXT_CAP_ID_MULTICAST                       (0x12)
#define PCIE_EXT_CAP_ID_PAGE_REQUEST                    (0x13)
#define PCIE_EXT_CAP_ID_RESIZABLE_BAR                   (0x15)
#define PCIE_EXT_CAP_ID_DYNAMIC_POWER_ALLOCATION        (0x16)
#define PCIE_EXT_CAP_ID_TPH                             (0x17)
#define PCIE_EXT_CAP_ID_LTR                             (0x18)
#define PCIE_EXT_CAP_ID_SECONDARY_PCIE                  (0x19)
#define PCIE_EXT_CAP_ID_PROTOCOL_MULTIPLEXING           (0x1A)
#define PCIE_EXT_CAP_ID_PASID                           (0x1B)
#define PCIE_EXT_CAP_ID_LNR                             (0x1C)
#define PCIE_EXT_CAP_ID_DPC                             (0x1D)
#define PCIE_EXT_CAP_ID_L1_PM_SUBSTATES                 (0x1E)
#define PCIE_EXT_CAP_ID_PRECISION_TIME_MEASUREMENT      (0x1F)
#define PCIE_EXT_CAP_ID_MPCIE                           (0x20)
#define PCIE_EXT_CAP_ID_FUNCTION_READINESS_STATUS       (0x21)
#define PCIE_EXT_CAP_ID_READINESS_TIME_REPORTING        (0x22)
#define PCIE_EXT_CAP_ID_DVSEC                           (0x23)                    
#define PCIE_EXT_CAP_ID_VF_RESIZEABLE_BAR               (0x24)    
#define PCIE_EXT_CAP_ID_DATA_LINK_FEATURE               (0x25)    
#define PCIE_EXT_CAP_ID_PHYSICAL_LAYER_16GTS            (0x26)        
#define PCIE_EXT_CAP_ID_LANE_MARGINING_AT_RX            (0x27)        
#define PCIE_EXT_CAP_ID_HIERARCHY_ID                    (0x28)
#define PCIE_EXT_CAP_ID_NATIVE_PCIE_ENCLOSURE_MNGMT     (0x29)            
#define PCIE_EXT_CAP_ID_PHYSICAL_LAYER_32GTS            (0x2A)        
#define PCIE_EXT_CAP_ID_ALTERNATE_PROTOCOL              (0x2B)    
#define PCIE_EXT_CAP_ID_SFI                             (0x2C)    

/**************************************************************
PCIe header status bit
**************************************************************/

#define PCIE_HEADER_STATUS_IMMEDIATE_READINESS          (0x1)
#define PCIE_HEADER_STATUS_INTERRUPT_STATUS             (0x8)
#define PCIE_HEADER_STATUS_CAPABILITIES_LIST            (0x10)
#define PCIE_HEADER_STATUS_MASTER_DATA_PARITY_ERROR     (0x100)
#define PCIE_HEADER_STATUS_SIGNALED_TARGET_ABORT        (0x800)
#define PCIE_HEADER_STATUS_RECEIVED_TARGET_ABORT        (0x1000)
#define PCIE_HEADER_STATUS_RECEIVED_MASTER_ABORT        (0x2000)
#define PCIE_HEADER_STATUS_SIGNALED_SYSTEM_ERROR        (0x4000)
#define PCIE_HEADER_STATUS_DETECTED_PARITY_ERROR        (0x8000)

/**************************************************************
PCIe header class code

https://pcisig.com/sites/default/files/files/PCI_Code-ID_r_1_11__v24_Jan_2019.pdf
**************************************************************/

#define PCIE_HEADER_CLASS_CODE_MASS_STORAGE_CONTROLLER                          (0x01)
#define PCIE_HEADER_CLASS_CODE_NETWORK_CONTROLLER                               (0x02)
#define PCIE_HEADER_CLASS_CODE_DISPLAY_CONTROLLER                               (0x03)
#define PCIE_HEADER_CLASS_CODE_MULTIMEDIA_DEVICE                                (0x04)
#define PCIE_HEADER_CLASS_CODE_MEMORY_CONTROLLER                                (0x05)
#define PCIE_HEADER_CLASS_CODE_BRIDGE_DEVICE                                    (0x06)
#define PCIE_HEADER_CLASS_CODE_SIMPLE_COMMUNICATION_CONTROLLER                  (0x07)
#define PCIE_HEADER_CLASS_CODE_BASE_SYSTEM_PERIPHERAL                           (0x08)
#define PCIE_HEADER_CLASS_CODE_INPUT_DEVICE                                     (0x09)
#define PCIE_HEADER_CLASS_CODE_DOCKING_STATION                                  (0x0A)
#define PCIE_HEADER_CLASS_CODE_PROCESSOR                                        (0x0B)
#define PCIE_HEADER_CLASS_CODE_SERIAL_BUS_CONTROLLER                            (0x0C)
#define PCIE_HEADER_CLASS_CODE_WIRELESS_CONTROLLER                              (0x0D)
#define PCIE_HEADER_CLASS_CODE_INTELLIGENT_IO_CONTROLLER                        (0x0E)
#define PCIE_HEADER_CLASS_CODE_SATELLITE_COMMUNICATION_CONTROLLER               (0x0F)
#define PCIE_HEADER_CLASS_CODE_ENCRYPTION_DECRYPTION_CONTROLLER                 (0x10)
#define PCIE_HEADER_CLASS_CODE_DATA_ACQUISITION_SIGNAL_PROCESSING_CONTROLLERS   (0x11)
#define PCIE_HEADER_CLASS_CODE_PROCESSING_ACCELERATORS                          (0x12)
#define PCIE_HEADER_CLASS_CODE_NON_ESSENTIAL_INSTRUMENTATION                    (0x13)
#define PCIE_HEADER_CLASS_CODE_UNDEFINED                                        (0xFF)
